import sys; sys.path.insert(0,'research')
from body_break_stress import *

BASE = dict(cost=2.0, end_hour=16, stop="daily_open", exit_="trail_half")
base_m = metrics(backtest(**BASE))
print("BASELINE  Logic A | flip ON | endHour 16 | stop daily_open | exit trail_half | cost 2.0")
row("BASELINE", base_m)
print("\n" + "="*118)
print("TEST 1 — COST SENSITIVITY")
for c in (2.0, 2.5, 3.0, 4.0):
    row(f"cost {c} pts", metrics(backtest(**{**BASE, "cost": c})))
print("\n" + "="*118)
print("TEST 2 — EXIT VARIATIONS (cost 2.0)")
for ex in ("trail_half","trail_body","trail_atr1.0","trail_atr1.5","1.5R","2R","2.5R"):
    row(ex + (" [baseline]" if ex=="trail_half" else ""), metrics(backtest(**{**BASE,"exit_":ex})), base_m)
print("\n" + "="*118)
print("TEST 3 — STOP VARIATIONS")
for sp in ("daily_open","daily_open+2","body_far","body_far+2","atr0.8","atr1.0","atr1.2"):
    row(sp + (" [baseline]" if sp=="daily_open" else ""), metrics(backtest(**{**BASE,"stop":sp})), base_m)
print("\n" + "="*118)
print("TEST 4 — TIME FILTERS")
row("no filter [baseline]", base_m)
row("entries only after 10:15", metrics(backtest(**{**BASE,"entry_after":615})), base_m)
row("entries only after 10:30", metrics(backtest(**{**BASE,"entry_after":630})), base_m)
row("no new entries after 14:00", metrics(backtest(**{**BASE,"entry_before":840})), base_m)
row("no new entries after 15:00", metrics(backtest(**{**BASE,"entry_before":900})), base_m)
print("\n" + "="*118)
print("TEST 5 — BODY QUALITY FILTER")
row("no filter [baseline]", base_m)
row("body > median", metrics(backtest(**{**BASE,"body_filter":"gt_median"})), base_m)
row("body within 25th-75th pct", metrics(backtest(**{**BASE,"body_filter":"iqr"})), base_m)
print("\n" + "="*118)
print("TEST 6 — FLIP CONTROL")
row("one flip per day [baseline behaviour]", base_m)
row("flip disabled entirely", metrics(backtest(**{**BASE,"flip":False})), base_m)
row("no flips after 13:00", metrics(backtest(**{**BASE,"flip_cutoff":13})), base_m)
row("no flips after 14:00", metrics(backtest(**{**BASE,"flip_cutoff":14})), base_m)
print("\n" + "="*118)
print("TEST 7 — PARTIAL EXIT")
row("no partial [baseline]", base_m)
row("50% at 1R, rest on trail_half", metrics(backtest(**{**BASE,"partial":True})), base_m)

print("\n" + "="*118)
print("COMBINATION TEST — stacking the two improvements")
b=metrics(backtest(**BASE))
row("baseline", b)
row("after 10:15", metrics(backtest(**{**BASE,"entry_after":615})), b)
row("partial 1R", metrics(backtest(**{**BASE,"partial":True})), b)
row("after 10:15 + partial 1R", metrics(backtest(**{**BASE,"entry_after":615,"partial":True})), b)
row("after 10:30 + partial 1R", metrics(backtest(**{**BASE,"entry_after":630,"partial":True})), b)
print("\nFINAL CANDIDATE AT ESCALATING COST")
for c in (2.0,2.5,3.0,4.0):
    m=metrics(backtest(**{**BASE,"entry_after":615,"partial":True,"cost":c}))
    if m: row(f"after 10:15 + partial, cost {c}", m)
