"""
Builds reports/GOLD_TREND_CHAMPION_ARCHIVE.pdf -- the complete technical record
of every formal version of the Gold Trend champion.

The document is written to be consumed by another model as much as by a person,
so it states parameters rather than describing them, uses NOT MEASURED where a
figure does not exist, and carries the full Pine for each version with no
elisions.

SOURCES, all read at build time -- nothing here is typed in by hand:
  research/champion_versions.json   metrics, generated by /tmp/genver2.py
  git 5388d74:strategies/gold_trend_strategy.pine   Original Champion
  git 927f485:strategies/gold_trend_E.pine          Config E
  git 927f485:strategies/gold_trend_G1.pine         Config G1
  HEAD    strategies/gold_trend_G1.pine             Config G1*
"""
import json, subprocess, textwrap
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (BaseDocTemplate, Frame, PageTemplate, Paragraph,
                                Spacer, Table, TableStyle, PageBreak,
                                KeepTogether, Preformatted)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

# The Pine sources use circled-number glyphs in their input group labels. The
# built-in Courier cannot encode them and silently substitutes a wrong
# character, which would corrupt the code on copy-paste -- the one thing this
# document exists to make reliable. FreeMono is monospace and covers every glyph these files use (verified with fontTools against U+24EA, U+24FF, U+24EB, U+24ED, U+2460-2464 and U+2500).
pdfmetrics.registerFont(TTFont("Mono", "/usr/share/fonts/truetype/freefont/FreeMono.ttf"))
CODEFONT = "Mono"

OUT = "reports/GOLD_TREND_CHAMPION_ARCHIVE.pdf"
J = json.load(open("research/champion_versions.json"))
DATA = J["data"]
V = {v["natural"]["version"]: v for v in J["versions"]}

PINES = {
    "ORIGINAL": ("git", "5388d74:strategies/gold_trend_strategy.pine"),
    "E":        ("git", "927f485:strategies/gold_trend_E.pine"),
    "G1":       ("git", "927f485:strategies/gold_trend_G1.pine"),
    "G1*":      ("file", "strategies/gold_trend_G1.pine"),
}

TITLES = {"ORIGINAL": "Version 1 — Original Champion",
          "E": "Version 2 — Config E",
          "G1": "Version 3 — Config G1",
          "G1*": "Version 4 — Config G1* (CURRENT SHIPPED)"}

ss = getSampleStyleSheet()
H1 = ParagraphStyle("H1", parent=ss["Heading1"], fontSize=16, spaceBefore=14,
                    spaceAfter=8, textColor=colors.HexColor("#1a1a1a"))
H2 = ParagraphStyle("H2", parent=ss["Heading2"], fontSize=12, spaceBefore=11,
                    spaceAfter=5, textColor=colors.HexColor("#333333"))
H3 = ParagraphStyle("H3", parent=ss["Heading3"], fontSize=10.5, spaceBefore=8,
                    spaceAfter=3, textColor=colors.HexColor("#444444"))
BODY = ParagraphStyle("BODY", parent=ss["BodyText"], fontSize=8.8, leading=11.6,
                      alignment=TA_LEFT, spaceAfter=4)
MONO = ParagraphStyle("MONO", parent=ss["BodyText"], fontName=CODEFONT,
                      fontSize=6.0, leading=6.9, spaceAfter=0, spaceBefore=0)
NOTE = ParagraphStyle("NOTE", parent=BODY, fontSize=8.0, leading=10.4,
                      textColor=colors.HexColor("#8a2b06"))

_cur = {"v": ""}


def _page(canv, doc):
    canv.saveState()
    canv.setFont("Helvetica", 7)
    canv.setFillColor(colors.HexColor("#777777"))
    canv.drawString(18 * mm, 287 * mm, "Gold Trend Champion Archive — XAUUSD 30m")
    if _cur["v"]:
        canv.drawRightString(192 * mm, 287 * mm, _cur["v"])
    canv.drawCentredString(105 * mm, 10 * mm, f"page {doc.page}")
    canv.setStrokeColor(colors.HexColor("#cccccc"))
    canv.line(18 * mm, 285 * mm, 192 * mm, 285 * mm)
    canv.restoreState()


class Mark(Spacer):
    """Zero-height flowable that stamps the running header for later pages."""
    def __init__(self, label):
        super().__init__(1, 0)
        self.label = label

    def draw(self):
        _cur["v"] = self.label


def tbl(rows, widths, size=7.4, header=True, align=None):
    t = Table(rows, colWidths=widths, repeatRows=1 if header else 0)
    st = [("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
          ("FONTSIZE", (0, 0), (-1, -1), size),
          ("LEADING", (0, 0), (-1, -1), size + 2.2),
          ("VALIGN", (0, 0), (-1, -1), "TOP"),
          ("TOPPADDING", (0, 0), (-1, -1), 2.2),
          ("BOTTOMPADDING", (0, 0), (-1, -1), 2.2),
          ("LEFTPADDING", (0, 0), (-1, -1), 4),
          ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#cfcfcf"))]
    if header:
        st += [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e8e8e8")),
               ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")]
        st += [("BACKGROUND", (0, i), (-1, i), colors.HexColor("#f7f7f7"))
               for i in range(2, len(rows), 2)]
    if align:
        for c in align:
            st.append(("ALIGN", (c, 0), (c, -1), "RIGHT"))
    t.setStyle(TableStyle(st))
    return t


def kv(pairs, w=(58 * mm, 116 * mm)):
    return tbl([["Field", "Value"]] + [[a, b] for a, b in pairs], w)


def code_block(path_spec, flow):
    kind, ref = path_spec
    src = (subprocess.run(["git", "show", ref], capture_output=True, text=True).stdout
           if kind == "git" else open(ref).read())
    src = src.replace("\t", "    ")
    lines = src.split("\n")
    wrapped = []
    for ln in lines:
        ln = ln.rstrip()
        if len(ln) <= 118:
            wrapped.append(ln)
        else:
            wrapped.extend(textwrap.wrap(ln, 118, subsequent_indent="        ",
                                         break_long_words=True,
                                         drop_whitespace=False) or [""])
    # chunk so ReportLab can break across pages
    CH = 46
    for i in range(0, len(wrapped), CH):
        flow.append(Preformatted("\n".join(wrapped[i:i + CH]), MONO))
    return len(lines)


def f(x, n=3):
    if x is None:
        return "NOT MEASURED"
    return f"{x:,.{n}f}"


def perf_table(rec):
    b25, b20 = rec["b25"], rec["b20"]
    rows = [["Metric", "25% DD budget", "20% DD budget"]]

    def add(label, key, n=3, pct=False):
        a, b = b25.get(key), b20.get(key)
        s = "%" if pct else ""
        rows.append([label, (f(a, n) + s) if a is not None else "NOT MEASURED",
                     (f(b, n) + s) if b is not None else "NOT MEASURED"])
    add("Risk per trade (solved)", "risk_pct", 3, True)
    add("Trades (total)", "n", 0)
    add("Trades long", "n_long", 0)
    add("Trades short", "n_short", 0)
    add("Win rate", "win_rate", 2, True)
    add("Average R", "avg_r", 3)
    add("Profit factor", "pf", 3)
    add("Net return", "net_pct", 1, True)
    add("CAGR", "cagr", 2, True)
    add("Max drawdown (historical)", "maxdd", 2, True)
    add("MAR (CAGR / MaxDD)", "mar", 3)
    add("Avg hold (30m bars)", "avg_bars", 1)
    add("Avg hold (days)", "avg_days", 2)
    add("Avg adds per trade", "avg_adds", 3)
    add("Avg winning trade (points)", "avg_win_pts", 2)
    add("Avg losing trade (points)", "avg_loss_pts", 2)
    add("Monte Carlo median DD", "mc_med", 2, True)
    add("Monte Carlo 95th pct DD", "mc_p95", 2, True)
    add("P(DD > 30%)", "mc_p30", 2, True)
    add("P(DD > 30%) std dev across seeds", "mc_p30_sd", 3)
    add("Profit factor, pre-2025", "pf_pre2025", 3)
    add("PF TRAIN (first third)", "pf_train", 3)
    add("PF VALID (middle third)", "pf_valid", 3)
    add("PF TEST (final third)", "pf_test", 3)
    add("PF first half", "pf_h1", 3)
    add("PF second half", "pf_h2", 3)
    add("Top 5 trades, % of NET profit", "top5_net", 1, True)
    add("Top 10 trades, % of NET profit", "top10_net", 1, True)
    add("Top 5 trades, % of GROSS profit", "top5_gross", 1, True)
    add("Top 10 trades, % of GROSS profit", "top10_gross", 1, True)
    return tbl(rows, (72 * mm, 51 * mm, 51 * mm))


def year_table(rec):
    b = rec["b25"]
    yrs = sorted(int(y) for y in b["pf_by_year"])
    rows = [["Year"] + [str(y) for y in yrs],
            ["Trades"] + [str(b["n_by_year"][str(y)]) for y in yrs],
            ["Profit factor"] + [f(b["pf_by_year"][str(y)], 3) for y in yrs]]
    return tbl(rows, [28 * mm] + [(146 / len(yrs)) * mm] * len(yrs))


def wf_table(rec):
    wf = rec["b25"]["walkforward"]
    rows = [["Fold"] + [str(i + 1) for i in range(len(wf))],
            ["Profit factor"] + [f(x, 3) for x in wf]]
    return tbl(rows, [28 * mm] + [(146 / len(wf)) * mm] * len(wf))


# ============================================================ rule specs
COMMON_ENTRY = [
    ("Bar close only", "Yes. Every condition is evaluated on the CLOSED bar. "
     "No intrabar evaluation, no varip, no request.security with lookahead."),
    ("Donchian breakout lookback",
     "24 bars = 12.0 hours on 30m. Pine: entryLenE = max(5, int(12.0*60/tfMin)). "
     "Applied with a [1] offset: donHi = ta.highest(high, 24)[1], "
     "donLo = ta.lowest(low, 24)[1], so a bar cannot trigger on its own extreme."),
    ("Regime EMA", "EMA(close, 1008 bars) = 21.0 days on 30m. "
     "Pine: regimeLenE = max(100, int(21.0*24*60/tfMin)). Bar-based, not calendar."),
    ("Fast SMA", "SMA(close, 384 bars) = 8.0 days on 30m. "
     "Pine: smaLenE = max(50, int(8.0*24*60/tfMin))."),
    ("Slope lookback", "96 bars = 2.0 days on 30m. "
     "Pine: slopeLenE = max(20, int(2.0*24*60/tfMin))."),
    ("LONG conditions (all required)",
     "1) close > ta.highest(high,24)[1]   2) close > EMA(close,1008)   "
     "3) close > SMA(close,384)   4) close > SMA(close,SLOW)   "
     "5) strategy.position_size == 0   6) bars since last exit > cooldown"),
    ("SHORT conditions (all required)",
     "1) close < ta.lowest(low,24)[1]   2) close < EMA(close,1008)   "
     "3) close < SMA(close,384)   4) close < SMA(close,SLOW)   "
     "5) EMA(close,1008) < EMA(close,1008)[96]  (regime mean actively FALLING; "
     "this fifth gate is LONG-side absent and is deliberate)   "
     "6) flat   7) cooldown satisfied"),
    ("Other entry filters", "NONE. No session filter, no volume filter, "
     "no volatility filter, no candlestick or level confluence."),
]

COMMON_EXIT_NOTES = [
    ("Number of exits", "Exactly one: a ratcheting chandelier trailing stop."),
    ("ATR period", "ATR(14), Wilder smoothing (RMA / ewm alpha=1/14)."),
    ("Trail anchor", "PREVIOUS bar's extreme. Long: high[1] - atr*mult. "
     "Short: low[1] + atr*mult. A bar can never move its own stop and then hit it."),
    ("Ratchet", "Monotone in the trade's favour only. "
     "Long: trailStop := max(trailStop, cand). Short: min(trailStop, cand)."),
    ("Profit target", "NONE."),
    ("Time exit", "NONE."),
    ("Breakeven stop", "NONE."),
    ("Max holding period", "Unbounded."),
]

COSTS = [("Commission", "USD 0.07 per contract (ounce) per side"),
         ("Slippage", "0.20 price points per side, applied against the trade"),
         ("Notional cap", "20x equity (maxLev). qty is capped at equity*20/close."),
         ("Overnight financing", "NOT MODELLED. At ~38.7% time in market and "
          "~2.6x time-weighted leverage, financing at 2-8% annual is an estimated "
          "2-8% of equity per year. Every return figure is that much optimistic."),
         ("Fill model", "Entry at the signal bar's close. Stops are gap-aware "
          "(filled at the open if the bar gapped through). A bar touching both a "
          "stop and a target resolves to the STOP.")]

SPECS = {
 "ORIGINAL": dict(
   ident=[("Label in research", "ORIGINAL / \"champion\" (backtest/champion.py defaults)"),
          ("Pine file", "strategies/gold_trend_strategy.pine"),
          ("Commit documented here", "5388d74 — last commit at which the Pine "
           "matches backtest/champion.py's ORIGINAL constants"),
          ("Validation certificate commit", "d04158c (DSR 0.9996, PBO 0.099)"),
          ("Change vs previous", "N/A — this is the baseline."),
          ("Was it shipped/live?", "Yes. This carried the early validation certificate.")],
   slow="SMA(close, 1008 bars) = 21.0 days",
   cooldown="3 bars",
   tighten="NONE. The trail multiple is a constant 4.24 x ATR(14) for the whole trade.",
   trail="4.24 x ATR(14). Pine: trailMultE = 6.0 * sqrt(15.0/tfMin) = 4.2426 at tfMin=30.",
   pyr=[("Maximum adds", "4"),
        ("Add trigger spacing", "every 1.5 x ATR of favourable movement from the last add price"),
        ("Add size formula", "aQty = equity * (riskE * shortRiskIfShort * pyrRisk) / 100 / "
         "(ATR_CURRENT * 4.24). NOTE: the ORIGINAL sizes adds on the CURRENT bar's ATR."),
        ("Regime multiplier on adds", "N/A — no regime multiplier exists in this version."),
        ("Open risk treatment", "Unbounded by design. Measured median open risk "
         "~2.1R, maximum >5R. Hard caps were tested and destroyed most of the return.")],
   sizing=[("Risk base", "strategy.equity (mark-to-market equity, not balance)"),
           ("Size formula", "qty = floor(min(equity * effRisk / 100 / stopDist, equity * 20 / close))"),
           ("stopDist", "ATR(14) * 4.24 — the same distance as the initial trail"),
           ("Short risk multiplier", "0.75 (shorts risk 75% of the long risk)"),
           ("Regime multiplier", "NONE"),
           ("Risk solved to 25% DD budget", "0.674%"),
           ("Risk solved to 20% DD budget", "0.534%")],
   diffs=["Baseline version. No prior version to differ from."]),

 "E": dict(
   ident=[("Label in research", "Config E"),
          ("Pine file", "strategies/gold_trend_E.pine"),
          ("Commit", "927f485 — \"Ship config E and config G1 as standalone strategies\""),
          ("Change vs previous", "Cooldown 3 -> 30 bars; slow SMA 21d -> 13d; "
           "trail tightening added; adds re-sized on ENTRY ATR instead of current ATR."),
          ("Was it shipped/live?", "Yes.")],
   slow="SMA(close, 630 bars) = 13.0 days",
   cooldown="30 bars",
   tighten="Once the trade's favourable excursion reaches 15.0 x ATR(at entry), "
           "the trail multiple changes from 4.24 to 2.0 x ATR(14) for the rest of "
           "the trade. Pine: effTrail = tightAfter > 0 and excAtr >= tightAfter ? "
           "tightTo : trailMultE, with tightAfter=15.0, tightTo=2.0.",
   trail="4.24 x ATR(14) initially, tightening to 2.0 (see above).",
   pyr=[("Maximum adds", "4"),
        ("Add trigger spacing", "every 1.5 x ATR of favourable movement"),
        ("Add size formula", "aQty = equity * (riskE * shortRiskIfShort * pyrRisk) / 100 / "
         "(ATR_AT_ENTRY * 4.24). CHANGED from ORIGINAL: uses the ATR captured at "
         "entry, not the current ATR. Current-ATR sizing shrinks the add exactly "
         "when volatility expands, which is when the trade is working."),
        ("Regime multiplier on adds", "N/A — no regime multiplier in this version."),
        ("Open risk treatment", "Unbounded by design, as ORIGINAL.")],
   sizing=[("Risk base", "strategy.equity"),
           ("Size formula", "qty = floor(min(equity * effRisk / 100 / stopDist, equity * 20 / close))"),
           ("stopDist", "ATR(14) * 4.24"),
           ("Short risk multiplier", "0.75"),
           ("Regime multiplier", "NONE"),
           ("Risk solved to 25% DD budget", "0.706% (Pine input default 0.705)"),
           ("Risk solved to 20% DD budget", "0.553%")],
   diffs=["Cooldown after an exit: 3 bars -> 30 bars.",
          "Slow SMA: 1008 bars (21 days) -> 630 bars (13 days).",
          "Trail tightening ADDED: 4.24 -> 2.0 x ATR after 15 x ATR of favourable excursion.",
          "Pyramid add sizing: current-bar ATR -> ATR captured AT ENTRY.",
          "Entry logic, exit anchor, ATR period, add count, add spacing, short risk "
          "multiplier and cost model are UNCHANGED."]),

 "G1": dict(
   ident=[("Label in research", "Config G1"),
          ("Pine file", "strategies/gold_trend_G1.pine (revision at commit 927f485)"),
          ("Commit", "927f485"),
          ("Change vs previous", "Adds a regime risk multiplier applied to the "
           "OPENING position only."),
          ("Was it shipped/live?", "Yes.")],
   slow="SMA(close, 630 bars) = 13.0 days", cooldown="30 bars",
   tighten="Identical to E: 4.24 -> 2.0 x ATR after 15 x ATR(entry) of excursion.",
   trail="4.24 x ATR(14) initially, tightening to 2.0.",
   pyr=[("Maximum adds", "4"),
        ("Add trigger spacing", "every 1.5 x ATR of favourable movement"),
        ("Add size formula", "aQty = equity * (riskE * shortRiskIfShort * pyrRisk) / 100 / "
         "(ATR_AT_ENTRY * 4.24)"),
        ("Regime multiplier on adds", "NO. The multiplier scales the OPENING unit only. "
         "Adds are sized at base risk. This is the single difference from G1*."),
        ("Open risk treatment", "Unbounded by design.")],
   sizing=[("Risk base", "strategy.equity"),
           ("Size formula", "qty = floor(min(equity * effRisk / 100 / stopDist, equity * 20 / close)) "
            "where effRisk = (wantShort ? riskE * 0.75 : riskE) * regimeMult"),
           ("stopDist", "ATR(14) * 4.24"),
           ("Short risk multiplier", "0.75"),
           ("Regime multiplier — trend factor f1",
            "trendStr = |close - EMA(close,1008)| / ATR(14).  "
            "f1 = 1.4 if trendStr > 6.00 else 0.8"),
           ("Regime multiplier — volatility factor f2",
            "volExp = SMA(ATR(14),20) / SMA(ATR(14),200).  "
            "f2 = 1.4 if volExp > 1.05 else 0.6"),
           ("Regime multiplier — combination",
            "regimeMult = clip(f1 * f2, 0.5, 2.0). Attainable values: "
            "0.8*0.6=0.48 -> clipped to 0.50; 0.8*1.4=1.12; 1.4*0.6=0.84; 1.4*1.4=1.96."),
           ("Risk solved to 25% DD budget", "0.724% (Pine input default 0.723)"),
           ("Risk solved to 20% DD budget", "0.567%")],
   diffs=["Regime risk multiplier ADDED, applied to the OPENING position only.",
          "Five new inputs: trendThr=6.0, expThr=1.05, upMult=1.4, dnMultT=0.8, dnMultV=0.6.",
          "Risk preset re-solved: 0.705 -> 0.723 (25% budget), 0.553 -> 0.567 (20%).",
          "Entry, exit, trail, tightening, add count, add spacing and add sizing are "
          "UNCHANGED from E."]),

 "G1*": dict(
   ident=[("Label in research", "Config G1* (\"G1 star\")"),
          ("Pine file", "strategies/gold_trend_G1.pine (current HEAD)"),
          ("Commit", "7b25357 — \"adopt G1*: regime multiplier extended to pyramid adds\""),
          ("Adoption date", "2026-08-05"),
          ("Change vs previous", "The G1 regime multiplier, captured at entry, now "
           "also scales every pyramid add."),
          ("Was it shipped/live?", "YES — this is the current shipped champion.")],
   slow="SMA(close, 630 bars) = 13.0 days", cooldown="30 bars",
   tighten="Identical to E and G1: 4.24 -> 2.0 x ATR after 15 x ATR(entry).",
   trail="4.24 x ATR(14) initially, tightening to 2.0.",
   pyr=[("Maximum adds", "4"),
        ("Add trigger spacing", "every 1.5 x ATR of favourable movement"),
        ("Add size formula", "aQty = equity * (riskE * shortRiskIfShort * pyrRisk * "
         "rmEntry) / 100 / (ATR_AT_ENTRY * 4.24)"),
        ("Regime multiplier on adds", "YES. rmEntry is the regimeMult value captured "
         "at ENTRY and held for the life of the trade (Pine: var float rmEntry, "
         "assigned on entry, reset to na when flat). Re-reading the live multiplier "
         "at each add would be intra-trade rebalancing — a different system, not tested."),
        ("Open risk treatment", "Unbounded by design. Mean adds per trade is 1.809, "
         "IDENTICAL to G1 — the trade paths are the same, only the add SIZE changes.")],
   sizing=[("Risk base", "strategy.equity"),
           ("Size formula", "qty = floor(min(equity * effRisk / 100 / stopDist, equity * 20 / close)) "
            "where effRisk = (wantShort ? riskE * 0.75 : riskE) * regimeMult"),
           ("stopDist", "ATR(14) * 4.24"),
           ("Short risk multiplier", "0.75"),
           ("Regime multiplier — trend factor f1",
            "trendStr = |close - EMA(close,1008)| / ATR(14).  f1 = 1.4 if trendStr > 6.00 else 0.8"),
           ("Regime multiplier — volatility factor f2",
            "volExp = SMA(ATR(14),20) / SMA(ATR(14),200).  f2 = 1.4 if volExp > 1.05 else 0.6"),
           ("Regime multiplier — combination", "regimeMult = clip(f1 * f2, 0.5, 2.0)"),
           ("Multiplier persistence", "rmEntry := regimeMult at entry; rmEntry := na when flat"),
           ("Risk solved to 25% DD budget", "0.646% (Pine input default 0.606 — see note)"),
           ("Risk solved to 20% DD budget", "0.506% (Pine input default 0.475 — see note)")],
   diffs=["Regime multiplier now applies to pyramid adds as well as the opening unit, "
          "using the value captured AT ENTRY.",
          "New Pine state variable: var float rmEntry, assigned at entry, reset on flat.",
          "Add-size line changed to: aRisk = (isLong ? riskE : riskE * shortRisk) * "
          "pyrRisk * nz(rmEntry, 1.0)",
          "Risk preset re-solved downward: 0.723 -> 0.606 (25% budget), 0.567 -> 0.475 (20%).",
          "Entry, exit, trail, tightening, add count, add spacing, add-ATR basis and "
          "the multiplier formula itself are UNCHANGED from G1."]),
}


# ============================================================ document body
def build():
    flow = []
    A = flow.append

    # ---------------------------------------------------------- title
    A(Mark("Front matter"))
    A(Paragraph("Gold Trend Champion — Complete Technical Archive", H1))
    A(Paragraph(
        "Machine-readable specification and performance record of every formal "
        "version of the Gold Trend strategy. Every parameter is stated, not "
        "described. Where a figure does not exist it reads NOT MEASURED. "
        "Rejected experiments are excluded by instruction.", BODY))
    A(Paragraph(f"Generated {DATA['start'][:10]} data through {DATA['end'][:10]}. "
                f"Build date 2026-08-05.", BODY))

    A(Paragraph("Current champion", H2))
    A(Paragraph("<b>Current champion is Config G1*.</b> It is preferred over G1 "
                "because at a matched 25% drawdown budget it more than halves the "
                "Monte Carlo tail — P(DD&gt;30%) 19.28% to 6.48% — while raising "
                "profit factor 2.005 to 2.157 and pre-2025 profit factor 1.513 to "
                "1.600, at equal MAR (2.510 vs 2.511). G1 was preferred over E for "
                "the same reason at smaller magnitude. E was preferred over the "
                "Original Champion on every metric simultaneously.", BODY))

    A(Paragraph("Versions in this document", H2))
    A(tbl([["#", "Version", "Pine source", "Shipped?"],
           ["1", "Original Champion", "git 5388d74:strategies/gold_trend_strategy.pine", "Yes (historic)"],
           ["2", "Config E", "git 927f485:strategies/gold_trend_E.pine", "Yes (historic)"],
           ["3", "Config G1", "git 927f485:strategies/gold_trend_G1.pine", "Yes (historic)"],
           ["4", "Config G1*", "strategies/gold_trend_G1.pine (HEAD, 7b25357)", "YES — CURRENT"]],
          (10 * mm, 38 * mm, 92 * mm, 34 * mm)))
    A(Paragraph("Excluded, with reason: <b>gold_trend_core.pine</b> (commit 346e300) "
                "is a superseded development build, never a formal baseline. "
                "<b>gold_trend_trailing.pine</b> (commit 23ab656) is the exit-experiment "
                "harness, not a strategy version. All rejected experiments — volatility "
                "targeting, level filters, PWH break, ORB, Quarterly Theory overlays, "
                "Bollinger squeeze gate — are excluded by instruction.", BODY))

    # ---------------------------------------------------------- data spec
    A(Paragraph("Global — Data specification", H2))
    A(kv([("Instrument", "XAUUSD (spot gold), OANDA feed"),
          ("Timeframe", "30 minutes, resampled from a native 15-minute export"),
          ("Source file", "data/xauusd_15m.csv.gz (157,366 15m bars)"),
          ("Bars (30m)", f"{DATA['bars']:,}"),
          ("Date range", f"{DATA['start']} to {DATA['end']} (UTC, tz-naive)"),
          ("Span", f"{DATA['years']:.2f} years, {DATA['weeks']} complete weeks"),
          ("Price range", f"low {DATA['px_min']:,.2f} to high {DATA['px_max']:,.2f}"),
          ("Data quality", "0 duplicate timestamps; 0 bars with high < low; "
           "5 zero-range bars; 394 gaps > 2h (weekends). No price spikes: the "
           "largest single-bar excess over both adjacent closes is 1.5%."),
          ("Regime coverage", "Gold ran 1,451 -> 5,598 (Jan 2026) -> 4,081. The "
           "sample contains a genuine 27% top-to-current decline as well as the "
           "2019-2025 bull run."),
          ("Signal evaluation", "CLOSED BARS ONLY for every version.")]))

    A(Paragraph("Global — Research protocol", H2))
    A(kv([("Drawdown budget solving",
           "Risk% is an OUTPUT, not an input. Bisection over risk% in [0.02, 4.0], "
           "18 iterations, accepting the largest risk whose historical max drawdown "
           "does not exceed the budget. Drawdown is monotone in risk% under "
           "fractional sizing, so bisection is sound. This is what makes versions "
           "with different natural leverage comparable."),
          ("Monte Carlo",
           "2,000-5,000 paths per seed x 5 seeds (11, 101, 2027, 55555, 987654). "
           "EQUITY-RELATIVE returns are shuffled, not raw dollars: under compounding "
           "the dollar series is path-dependent and reshuffling it is meaningless. "
           "Reported: median max DD, 95th percentile max DD, P(DD > 30%), and the "
           "standard deviation of P(DD>30%) across seeds."),
          ("\"Pre-2025\"", "All trades whose ENTRY bar falls in calendar year 2024 or "
           "earlier. This deliberately excludes the 2025-2026 trend, which is the "
           "largest in the sample. Profit factor is recomputed on that subset."),
          ("TRAIN / VALID / TEST", "The trade sequence split into equal thirds by "
           "trade index (not by time)."),
          ("Anchored walk-forward", "Six equal forward windows spanning bars "
           "31,478 to 78,695 (the final 60% of the sample), expanding anchor."),
          ("Concentration", "Trades sorted by P&L descending; the top 5 and top 10 "
           "expressed as a percentage of NET profit and of GROSS profit. NET is the "
           "harsher and more informative measure."),
          ("Costs", "Commission USD 0.07/contract/side and slippage 0.20 points/side "
           "applied in every figure in this document.")]))

    # ---------------------------------------------------------- comparison
    A(PageBreak())
    A(Mark("Cross-version comparison"))
    A(Paragraph("Global — Cross-version comparison, 25% drawdown budget", H2))
    keys = ["ORIGINAL", "E", "G1", "G1*"]
    rows = [["Metric"] + ["Original", "E", "G1", "G1* (current)"]]
    for lab, k, n, pc in (("Risk per trade (solved)", "risk_pct", 3, True),
                          ("Trades", "n", 0, False),
                          ("Long / short", None, 0, False),
                          ("Win rate", "win_rate", 2, True),
                          ("Average R", "avg_r", 3, False),
                          ("Profit factor", "pf", 3, False),
                          ("Net return", "net_pct", 1, True),
                          ("CAGR", "cagr", 2, True),
                          ("Max drawdown", "maxdd", 2, True),
                          ("MAR", "mar", 3, False),
                          ("Monte Carlo median DD", "mc_med", 2, True),
                          ("MC 95th pct DD", "mc_p95", 2, True),
                          ("P(DD > 30%)", "mc_p30", 2, True),
                          ("PF pre-2025", "pf_pre2025", 3, False),
                          ("PF TRAIN/VALID/TEST", None, 0, False),
                          ("Avg hold (bars)", "avg_bars", 1, False),
                          ("Avg adds per trade", "avg_adds", 3, False),
                          ("Top 5 trades, % of NET", "top5_net", 1, True),
                          ("Top 10 trades, % of NET", "top10_net", 1, True)):
        r = [lab]
        for kk in keys:
            b = V[kk]["b25"]
            if lab == "Long / short":
                r.append(f"{b['n_long']} / {b['n_short']}")
            elif lab == "PF TRAIN/VALID/TEST":
                r.append(f"{b['pf_train']:.2f}/{b['pf_valid']:.2f}/{b['pf_test']:.2f}")
            else:
                r.append(f(b[k], n) + ("%" if pc else ""))
        rows.append(r)
    A(tbl(rows, (48 * mm, 31 * mm, 31 * mm, 31 * mm, 33 * mm)))

    A(Paragraph("Global — Cross-version comparison, 20% drawdown budget", H2))
    rows2 = [["Metric", "Original", "E", "G1", "G1* (current)"]]
    for lab, k, n, pc in (("Risk per trade (solved)", "risk_pct", 3, True),
                          ("Profit factor", "pf", 3, False),
                          ("CAGR", "cagr", 2, True),
                          ("MAR", "mar", 3, False),
                          ("Monte Carlo median DD", "mc_med", 2, True),
                          ("P(DD > 30%)", "mc_p30", 2, True),
                          ("PF pre-2025", "pf_pre2025", 3, False),
                          ("Top 5 trades, % of NET", "top5_net", 1, True)):
        rows2.append([lab] + [f(V[kk]["b20"][k], n) + ("%" if pc else "") for kk in keys])
    A(tbl(rows2, (48 * mm, 31 * mm, 31 * mm, 31 * mm, 33 * mm)))

    # ---------------------------------------------------------- caveats
    A(Paragraph("Global — Known limitations and caveats", H2))
    A(Paragraph(
        "<b>1. Profit concentration.</b> At the 25% budget the top 5 of 711 trades "
        "(0.7%) carry 42.3% of NET profit for G1*, and the top 10 carry "
        f"{V['G1*']['b25']['top10_net']:.1f}%. The strategy is a small number of large "
        "winners plus a long tail of small losses. This is inherent to trend "
        "following with wide trails and pyramiding, and it means live results "
        "depend heavily on catching those few moves.", BODY))
    A(Paragraph(
        "<b>2. Gold-only scope.</b> US30 was withdrawn from the protocol by user "
        "directive on 2026-08-05. Before withdrawal, G1* FAILED the US30 transfer "
        "test: P(DD&gt;30%) rose from 36% to 53%. The claim the evidence supports "
        "is \"better on gold\", not \"better\".", BODY))
    A(Paragraph(
        "<b>3. Execution sensitivity.</b> Break-even is roughly 1.6 points of "
        "slippage. At 0.50 points returns fall sharply; at 1.50 points the system "
        "is dead. Overnight financing is not modelled at all (estimated 2-8% of "
        "equity per year).", BODY))
    A(Paragraph(
        "<b>4. Walk-forward fold 1 degrades for G1*.</b> Fold 1 of 6 falls to "
        f"PF {V['G1*']['b25']['walkforward'][0]:.3f}; folds 2-6 improve on G1.", BODY))
    A(Paragraph(
        "<b>5. Whole-contract granularity.</b> Below roughly USD 25,000 at current "
        "gold prices the integer-lot floor causes a large fraction of signals to be "
        "skipped and the system loses money. All research figures use FRACTIONAL "
        "sizing (frac_qty=True); the Pine uses math.floor and will therefore differ "
        "on small accounts.", BODY))
    A(Paragraph(
        "<b>6. Parameter selection is not virgin out-of-sample.</b> Parameters were "
        "chosen across earlier rounds with knowledge of the full sample.", BODY))
    A(Paragraph(
        "<b>7. Never seen a multi-year gold bear market.</b> The sample contains "
        "three down/flat years (2021, 2022, 2026) but no sustained bear market.", BODY))

    # ---------------------------------------------------------- bugs
    A(Paragraph("Global — Bugs discovered during research that affect interpretation", H2))
    A(tbl([["ID", "Defect", "Effect on earlier numbers"],
           ["BUG-029", "In backtest/orb.py, a bar that hit both target and stop fell "
            "through to the session-close time exit instead of resolving to the loss.",
            "ORB baseline PF fell 1.13 -> 0.99 after the fix. Caught because a "
            "strategy AND its mirror were both profitable."],
           ["BUG-030", "Pyramid adds filled at a stale trigger price when the bar "
            "gapped past it.",
            "Champion PF fell 1.646 -> 1.623 after the gap-aware fix. Caught by a "
            "+5.4 trillion percent result on a related arm."],
           ["np.floor sizing", "Integer position sizing silently rejected 788 of 789 "
            "US30 entries, reporting n=1.",
            "Any pre-fix US30 figure is void. frac_qty flag added."],
           ["stop_atr not passed", "champion.py did not pass stop_atr to exit_lab, so "
            "the exit used a 4.0 default while trailing at 4.24.",
            "All pre-fix champion figures were computed with a mismatched initial stop."],
           ["risk_series not applied to adds", "risk_series scaled the opening unit "
            "only. Correct for G1 by design, but it made a volatility-targeting test "
            "measure the wrong thing.",
            "Discovered via an identity control (VT ATR14 must reproduce E exactly). "
            "This is what led to G1*."],
           ["G1 constant mismatch", "research/voltarget.py g1_series() used 1.30/0.85 "
            "at a 1.10 volatility threshold; the shipped Pine and "
            "STRATEGY_SPECIFICATION.md section 7 use 1.4/0.8/0.6 at 1.05. The two "
            "differ on 100% of bars.",
            "The G1 and G1* figures previously published in RESULTS_LEDGER.md and the "
            "specification were produced with the HARNESS constants. Every figure in "
            "THIS document uses the PINE constants and is therefore authoritative for "
            "the shipped code. See the note below."]],
          (22 * mm, 74 * mm, 78 * mm)))

    A(Paragraph("Note on the G1 constant mismatch", H3))
    A(Paragraph(
        "The discrepancy favours the shipped code. Recomputed at a 25% drawdown "
        "budget, G1* with the PINE constants gives PF 2.157, MAR 2.511, "
        "P(DD&gt;30%) 6.48%, pre-2025 PF 1.600. The previously published harness "
        "figures were PF 2.175, MAR 2.431, P(DD&gt;30%) 9.85%, pre-2025 PF 1.520. "
        "The Pine is better on MAR, on the Monte Carlo tail and on the pre-2025 "
        "regime split. The earlier numbers were therefore conservative, but they "
        "did not describe the code that ships.", NOTE))

    # ---------------------------------------------------------- per version
    for vk in ("ORIGINAL", "E", "G1", "G1*"):
        sp, rec = SPECS[vk], V[vk]
        A(PageBreak())
        A(Mark(TITLES[vk]))
        A(Paragraph(TITLES[vk], H1))

        A(Paragraph("1. Identity and provenance", H2))
        A(kv(sp["ident"]))

        A(Paragraph("2. Complete rule specification", H2))
        A(Paragraph("2.1 Entry", H3))
        entry = list(COMMON_ENTRY)
        entry.insert(4, ("Slow SMA", sp["slow"]))
        entry.append(("Cooldown after an exit", sp["cooldown"] +
                      " — a new entry requires barsSinceExit > cooldown."))
        A(kv(entry))

        A(Paragraph("2.2 Exit", H3))
        ex = [("Initial trail multiple", sp["trail"])] + list(COMMON_EXIT_NOTES)
        ex.insert(3, ("Tightening rule", sp["tighten"]))
        A(kv(ex))

        A(Paragraph("2.3 Pyramiding", H3))
        A(kv(sp["pyr"]))

        A(Paragraph("2.4 Position sizing and risk", H3))
        A(kv(sp["sizing"]))

        A(Paragraph("2.5 Costs and execution assumptions used in research", H3))
        A(kv(COSTS))

        A(Paragraph("3. Full performance record", H2))
        A(Paragraph(
            f"Gold XAUUSD 30m, {DATA['bars']:,} bars, {DATA['start'][:10]} to "
            f"{DATA['end'][:10]} ({DATA['years']:.2f} years). Costs applied. "
            "Risk% is the SOLVED value that produced the stated drawdown.", BODY))
        A(perf_table(rec))

        A(Paragraph("3.1 Year by year (25% drawdown budget)", H3))
        A(year_table(rec))
        A(Paragraph("Down/flat years in this sample are 2021 (gold -4.3%), "
                    "2022 (-0.3%) and 2026 (-6.0%).", BODY))

        A(Paragraph("3.2 Anchored walk-forward, 6 folds (25% drawdown budget)", H3))
        A(wf_table(rec))

        A(Paragraph("3.3 Reference: same configuration at a flat 1.0% risk", H3))
        nt = rec["natural"]
        A(tbl([["Risk", "Trades", "Profit factor", "Net return", "Max DD"],
               ["1.000%", str(nt["n"]), f(nt["pf"], 3), f(nt["net_pct"], 1) + "%",
                f(nt["maxdd"], 2) + "%"]], (34 * mm, 34 * mm, 36 * mm, 36 * mm, 34 * mm)))

        A(Paragraph("5. Differences from the previous version", H2))
        for d in sp["diffs"]:
            A(Paragraph("• " + d, BODY))

        A(PageBreak())
        A(Paragraph(f"4. Complete Pine Script — {TITLES[vk]}", H2))
        kind, ref = PINES[vk]
        A(Paragraph(
            f"Source: {'git ' + ref if kind == 'git' else ref}. Reproduced in full "
            "with no elisions. Inputs carry the exact defaults that reproduce the "
            "configuration documented above. Closed-bar only.", BODY))
        n = code_block(PINES[vk], flow)
        A(Spacer(1, 4))
        A(Paragraph(f"— end of Pine source ({n} lines) —", BODY))

    doc = BaseDocTemplate(OUT, pagesize=A4,
                          leftMargin=18 * mm, rightMargin=18 * mm,
                          topMargin=22 * mm, bottomMargin=16 * mm,
                          title="Gold Trend Champion Archive",
                          author="Trade Cartel research")
    frame = Frame(18 * mm, 16 * mm, 174 * mm, 262 * mm, id="f")
    doc.addPageTemplates([PageTemplate(id="all", frames=[frame], onPage=_page)])
    doc.build(flow)
    print(f"WROTE {OUT}")


if __name__ == "__main__":
    build()
