"""Write the README that ships beside the Parquet file.

Every number is read back out of audit.json / verify.json / the manifests rather
than retyped, so the README cannot drift from the artefact it describes.
"""
import csv, datetime as dt, json, os
from zoneinfo import ZoneInfo

BASE = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
PROC, LOGS = os.path.join(BASE, "processed"), os.path.join(BASE, "logs")
NAME = "GOLD_XAUUSD_DUKASCOPY_TICKS_2025-08-21_to_2026-08-20"
MEL, UTC = ZoneInfo("Australia/Melbourne"), dt.timezone.utc


def human(n):
    x = float(n)
    for u in ("B", "KiB", "MiB", "GiB"):
        if x < 1024 or u == "GiB":
            return f"{n:,} B" if u == "B" else f"{x:.2f} {u}"
        x /= 1024


def main():
    A = json.load(open(os.path.join(LOGS, "audit.json")))
    V = json.load(open(os.path.join(LOGS, "verify.json")))
    pq_path = os.path.join(PROC, NAME + ".parquet")
    size = os.path.getsize(pq_path)

    mel_start = dt.datetime(2025, 8, 21, 0, 0, 0, 0, tzinfo=MEL)
    mel_end = dt.datetime(2026, 8, 20, 23, 59, 59, 999000, tzinfo=MEL)

    rows = list(csv.DictReader(open(os.path.join(LOGS, "manifest_by_day.csv"))))
    retries = sum(int(r["retries"]) for r in rows)
    raw_bytes = sum(int(r["raw_bytes"]) for r in rows)

    sp, tpd, gb = A["spread_stats"], A["ticks_per_day"], A["gaps_by_class"]
    L, W = [], None
    W = L.append

    W("=" * 78)
    W("GOLD / XAUUSD  -  RAW TICK DATASET  -  DUKASCOPY  -  ONE YEAR")
    W("=" * 78)
    W("")
    W("SOURCE")
    W("    Dukascopy Bank SA historical tick feed (authentic BI5 hourly tick files)")
    W("    https://datafeed.dukascopy.com/datafeed/XAUUSD/{YYYY}/{MM0}/{DD}/{HH}h_ticks.bi5")
    W("    MM0 is Dukascopy's zero-indexed month: January=00 ... December=11.")
    W("    Downloaded straight from that feed. Not candles, not 1-minute bars, not")
    W("    another broker, not a vendor mirror, not a resampled product.")
    W("")
    W("SYMBOL")
    W("    XAUUSD  (spot gold vs US dollar)")
    W("")
    W("DATA TYPE")
    W("    Raw tick / quote data - every bid/ask update Dukascopy published.")
    W("")
    W("REQUESTED MELBOURNE PERIOD")
    W(f"    {mel_start.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}")
    W("    to")
    W(f"    {mel_end.strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]}   (Australia/Melbourne)")
    W("")
    W("UTC REQUEST BOUNDARIES")
    W(f"    {mel_start.astimezone(UTC).strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]} UTC"
      f"   (Melbourne {mel_start.strftime('%z')} {mel_start.tzname()})")
    W("    to")
    W(f"    {mel_end.astimezone(UTC).strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]} UTC"
      f"   (Melbourne {mel_end.strftime('%z')} {mel_end.tzname()})")
    W("")
    W("    Computed with zoneinfo, not a fixed offset. The window spans BOTH")
    W("    Australian offsets, so a hard-coded UTC+10 would have been wrong for")
    W("    182 days of it. The two transitions inside the period:")
    W("        2025-10-05  02:00 -> 03:00 Melbourne   AEST +10:00 -> AEDT +11:00")
    W("        2026-04-05  03:00 -> 02:00 Melbourne   AEDT +11:00 -> AEST +10:00")
    W("    Both endpoints fall in AEST (+10). Every Australian offset is a whole")
    W("    number of hours, so both boundaries land exactly on a UTC hour. The")
    W("    boundary filter was still applied explicitly after assembling the whole")
    W("    hourly download, and is reported below.")
    W("")
    W("TOTAL TICKS")
    W(f"    {A['total_ticks']:,}")
    W("")
    W(f"FIRST TICK UTC            {A['first_tick_utc']}")
    W(f"LAST TICK UTC             {A['last_tick_utc']}")
    W(f"FIRST TICK MELBOURNE      {A['first_tick_melbourne']}")
    W(f"LAST TICK MELBOURNE       {A['last_tick_melbourne']}")
    W("")
    W("COLUMNS")
    W("    1  timestamp_utc        timestamp[ms, tz=UTC]  instant of the quote")
    W("    2  timestamp_melbourne  timestamp[ms]          Australia/Melbourne WALL CLOCK,")
    W("                                                   DST-correct (AEST+10 / AEDT+11).")
    W("                                                   Stored NAIVE deliberately so any")
    W("                                                   reader shows the literal local")
    W("                                                   time rather than re-rendering a")
    W("                                                   UTC instant.")
    W("    3  bid                  double                 bid price, USD/oz")
    W("    4  ask                  double                 ask price, USD/oz")
    W("    5  bid_volume           float                  Dukascopy native units")
    W("    6  ask_volume           float                  Dukascopy native units")
    W("    7  mid                  double                 (bid + ask) / 2   [derived]")
    W("    8  spread               double                 ask - bid         [derived]")
    W("")
    W("TIMESTAMP PRECISION")
    W("    MILLISECOND - the native precision of the Dukascopy BI5 record, which")
    W("    stores a millisecond offset from the start of each hour. Nothing is")
    W(f"    rounded to seconds or minutes: {A['total_ticks']:,} rows are stored at ms")
    W("    resolution and sub-second components are present throughout.")
    W("")
    W("BID/ASK")
    W("    YES - both stored unmodified at full source precision. mid and spread")
    W("    are ADDED columns, never substitutes; bid and ask remain in the data.")
    W("")
    W("VOLUME")
    W("    bid_volume, ask_volume  (both present on every tick)")
    W("    Dukascopy's own units - a retail aggregator's book, not exchange volume.")
    W("")
    W("PARQUET COMPRESSION")
    W("    ZSTD (level 9), Parquet format version 2.6")
    W("")
    W("FILE SIZE")
    W(f"    {size:,} bytes   ({human(size)})")
    W("")
    W("SHA256")
    W(f"    {V['sha256']}")
    W("")
    W("-" * 78)
    W("DATA QUALITY")
    W("-" * 78)
    W(f"DUPLICATE EXACT ROWS          {A['exact_duplicate_rows']:,}")
    W(f"DUPLICATE TIMESTAMPS          {A['duplicate_timestamps']:,}")
    W("    Distinct quotes that share a millisecond. Dukascopy timestamps to the")
    W("    millisecond and gold updates faster than that, so these are legitimate")
    W("    separate quotes, NOT duplicates. They are retained.")
    W(f"BID > ASK                     {A['bid_gt_ask']:,}")
    W(f"INVALID PRICE ROWS            {A['invalid_price_rows']:,}")
    W("    (null bid, null ask, bid<=0, ask<=0, or bid>ask)")
    W(f"ZERO SPREAD                   {A['zero_spread']:,}")
    W(f"NEGATIVE SPREAD               {A['negative_spread']:,}")
    W(f"EXTREME SPREAD (> $5.00)      {A['extreme_spread_gt_5.0']:,}")
    W(f"TIMESTAMPS OUT OF ORDER       {A['timestamps_out_of_order']:,}")
    W("")
    W("Spread distribution (USD):")
    W(f"    min {sp['min']:.3f}   p01 {sp['p01']:.3f}   median {sp['median']:.3f}   mean {sp['mean']:.3f}")
    W(f"    p99 {sp['p99']:.3f}   p99.99 {sp['p99_99']:.3f}   max {sp['max']:.3f}")
    pr = A["price_range"]
    W(f"Price range: bid {pr['bid_min']:,.3f} .. {pr['bid_max']:,.3f}"
      f"    ask {pr['ask_min']:,.3f} .. {pr['ask_max']:,.3f}")
    W("")
    W("NOTHING WAS DELETED. No tick was dropped for being unusual. Wide spreads,")
    W("zero-volume quotes and repeated prices are retained exactly as delivered and")
    W("reported here so you can filter them yourself if your model needs to.")
    W("")
    W("-" * 78)
    W("DOWNLOAD COMPLETENESS")
    W("-" * 78)
    W(f"HOURS REQUESTED               {A['hours_requested']:,}   (every UTC hour in the window)")
    W(f"HOURS WITH TICKS              {A['hours_with_ticks']:,}")
    W(f"EMPTY HOURS                   {A['hours_empty']:,}")
    W(f"UNRESOLVED DOWNLOAD HOURS     {A['unresolved_download_hours']}")
    if A["unresolved_download_hours"] == 0:
        W("    Zero. Every one of the 8,760 requested hours was fetched and answered.")
    else:
        W("    NOT ZERO - the following hours never resolved after all retries:")
        for u in A["unresolved_download_hours_list"]:
            W(f"        {u['hour_utc']}  {u['status']}  {u.get('errors')}")
    W(f"    HTTP retries across the whole run: {retries}")
    W("")
    W("EMPTY HOURS: EXPECTED CLOSED MARKET vs UNEXPECTED MISSING DATA")
    W("")
    W("    An empty hour is a real answer from Dukascopy, not a failure. Gold trades")
    W("    24x5 and is SHUT for most empty hours, so each one is classified against")
    W("    the actual session calendar in NEW YORK time - the clock the settlement")
    W("    break and the weekly open/close follow.")
    W("")
    W(f"    EXPECTED CLOSED-MARKET EMPTY PERIODS   {A['hours_empty_expected_closed_market']:,}")
    for k, v in A["empty_hour_reasons"].items():
        W(f"        {v:>6,}   {k}")
    W("")
    W(f"    UNEXPECTED MISSING DATA                {A['hours_empty_unexpected']:,}")
    if A["hours_empty_unexpected"] == 0:
        W("        None. Every empty hour is attributable to a scheduled closure.")
    else:
        W("        Hours inside expected trading time for which Dukascopy published")
        W("        no ticks at all. Reported, never interpolated:")
        for e in A["hours_empty_unexpected_list"][:60]:
            W(f"            {e['hour_utc']}   {e['reason']}")
        if A["hours_empty_unexpected"] > 60:
            W(f"            ... and {A['hours_empty_unexpected']-60} more"
              f" (full list: logs/audit.json)")
    W("")
    W("-" * 78)
    W("DATA GAPS")
    W("-" * 78)
    W(f"Intervals between consecutive ticks longer than {A['gap_threshold_minutes']:.0f} minutes:"
      f"  {A['gaps_total']:,}")
    for k in sorted(gb, key=lambda x: -gb[x]):
        W(f"    {k:<14s} {gb[k]:>7,}")
    W("")
    if A["gaps_unexplained_count"] == 0:
        W("    Every gap is attributable to a known closure: the weekend shutdown,")
        W("    gold's daily NY 17:00-18:00 settlement break, or a listed exchange")
        W("    holiday. NO UNEXPLAINED MISSING PERIODS.")
    else:
        W(f"    {A['gaps_unexplained_count']} gap(s) are NOT attributable to a weekend, the daily")
        W("    maintenance break, or a listed holiday. They total")
        W(f"    {A['gaps_unexplained_total_minutes']:.1f} MINUTES across the entire year, the longest being")
        W(f"    {A['gaps_unexplained_longest_minutes']:.1f} minutes. Every one falls in a known thin-liquidity")
        W("    window - the first half hour after the Sunday reopen, the minutes")
        W("    just after a daily reopen, or the Black Friday overnight session -")
        W("    so they read as the book going quiet rather than as feed outages.")
        W("    They are listed rather than absorbed into the closure rules:")
        for g in A["gaps_unexplained_top50"][:20]:
            W(f"        {g['minutes']:>9.1f} min   {g['start_utc']}  ->  {g['end_utc']}")
        W("    These are periods Dukascopy itself published no ticks for. They are")
        W("    reported, not patched: no value is interpolated anywhere in this file.")
    W("")
    W("Longest gaps overall:")
    for g in A["gaps_longest_10"]:
        W(f"    {g['minutes']:>9.1f} min  {g['class']:<12s} {g['start_utc']} -> {g['end_utc']}")
    W("")
    W("-" * 78)
    W("COVERAGE BREAKDOWN  (Australia/Melbourne calendar)")
    W("-" * 78)
    W(f"Days requested:  {A['days_requested_melbourne']}")
    W(f"Days with data:  {A['days_with_data']}")
    W(f"Days with none:  {A['days_with_no_data_count']}   (weekends and holidays - itemised below)")
    W("")
    W("Ticks per day with data:")
    W(f"    mean    {tpd['mean']:>12,.0f}")
    W(f"    median  {tpd['median']:>12,.0f}")
    W(f"    min     {tpd['min']:>12,}   ({tpd['min_day']})")
    W(f"    max     {tpd['max']:>12,}   ({tpd['max_day']})")
    W("")
    W("BY YEAR")
    W(f"    {'year':<6} {'ticks':>16} {'trading days':>14}")
    for y in sorted(A["by_year"]):
        v = A["by_year"][y]
        W(f"    {y:<6} {v['ticks']:>16,} {v['trading_days']:>14}")
    W("")
    W("BY MONTH  (use this to spot a missing chunk at a glance)")
    W(f"    {'month':<9} {'ticks':>16} {'days':>6} {'ticks/day':>12}")
    for m in sorted(A["by_month"]):
        v = A["by_month"][m]
        W(f"    {m:<9} {v['ticks']:>16,} {v['trading_days']:>6} "
          f"{v['ticks']//max(v['trading_days'],1):>12,}")
    W("")
    W("Days with no data at all, and why:")
    for dd, why in sorted(A["missing_day_reasons"].items()):
        W(f"    {dd}   {why}")
    W("")
    W("-" * 78)
    W("VERIFICATION PERFORMED")
    W("-" * 78)
    W("The Parquet file was closed, then reopened by a SEPARATE process, which")
    W("confirmed:")
    W("     1. row count matches the Parquet footer")
    W("     2. first row matches the audit")
    W("     3. last row matches the audit")
    W("     4. timestamps are non-decreasing (source order preserved, never sorted)")
    W("     5. millisecond precision retained - not rounded to seconds or minutes")
    W("     6. bid present and non-null on every row")
    W("     7. ask present and non-null on every row")
    W("     8. mid == (bid+ask)/2 exactly after the round trip")
    W("     9. bid_volume and ask_volume present and non-null on every row")
    W("    10. no accidental downsampling - the row count equals the sum of the")
    W("        per-hour tick counts taken from the raw BI5 files")
    W("    11. every tick falls inside the requested Melbourne/UTC boundaries")
    W("    12. the file opens cleanly with pyarrow and pandas")
    W("")
    W("    Plus the check that actually proves serialisation altered nothing: 40")
    W("    randomly chosen hours were re-decoded straight from the raw .bi5 files")
    W("    and compared row-for-row against the Parquet body - including that")
    W("    bid*1000 returns the source's original integer point value, which is")
    W("    what would fail first if float precision had been lost.")
    W("")
    W(f"    RESULT: {'ALL CHECKS PASSED' if not V['failures'] else 'FAILURES: ' + ', '.join(V['failures'])}")
    W("")
    W("-" * 78)
    W("HOW TO READ IT  (self-contained: no Dukascopy access, no API key, no")
    W("downloader, no repository and no special environment required)")
    W("-" * 78)
    W("    import pandas as pd")
    W(f"    df = pd.read_parquet('{NAME}.parquet')")
    W("")
    W("    # lazily, if the whole year will not fit in memory:")
    W("    import pyarrow.parquet as pq")
    W(f"    pf = pq.ParquetFile('{NAME}.parquet')")
    W("    for batch in pf.iter_batches(batch_size=1_000_000):")
    W("        ...")
    W("")
    W("    # or with DuckDB, no load at all:")
    W(f"    SELECT * FROM '{NAME}.parquet'")
    W("    WHERE timestamp_melbourne >= TIMESTAMP '2026-01-01';")
    W("")
    W("    Only a standard Parquet reader is needed. ZSTD is built into pyarrow,")
    W("    polars, duckdb, pandas and Spark.")
    W("")
    W("-" * 78)
    W("PROVENANCE")
    W("-" * 78)
    W(f"    Raw source mirror: {human(raw_bytes)} of untouched Dukascopy .bi5 bytes,")
    W("    exactly as served, kept at raw/YYYY/MM/DD/HHh_ticks.bi5.")
    W("    A SHA256 for every hourly file is in logs/manifest_by_hour.csv, and")
    W("    logs/manifest_by_day.csv is the per-day roll-up with status, tick counts,")
    W("    first/last timestamps, retry counts and errors. The mirror can therefore")
    W("    be re-verified byte-for-byte without re-downloading it.")
    W(f"    Built: {dt.datetime.now(UTC).strftime('%Y-%m-%d %H:%M:%S')} UTC")
    W("")
    W("-" * 78)
    W("NOTES AND CAVEATS")
    W("-" * 78)
    W("    * XAUUSD is OTC spot gold. There is no consolidated tape, so tick counts")
    W("      and spreads reflect DUKASCOPY's liquidity, not the whole market's.")
    W("      Another broker's tick stream for the same period will differ.")
    W("    * Volumes are Dukascopy's own units from a retail aggregator's book.")
    W("      Treat them as relative activity, not as exchange volume.")
    W("    * Gold halts daily for the NY 17:00-18:00 settlement break. Its Melbourne")
    W("      clock time moves with BOTH the US and Australian DST calendars, so it")
    W("      sits at 07:00-08:00, 08:00-09:00 or 09:00-10:00 Melbourne depending on")
    W("      the date. Do not assume one fixed local window.")
    W("    * Ticks are quote updates, not trades. A tick means the bid or ask moved.")
    W("=" * 78)

    out = os.path.join(PROC, NAME + "_README.txt")
    open(out, "w").write("\n".join(L) + "\n")
    print(f"-> {out}  ({os.path.getsize(out):,} bytes)")


if __name__ == "__main__":
    main()
